# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:8000/auth/signup
{:
  "username": "MM10",
  "email": "MM10@gmail.com",
  "password": "mm12061382",
  "is_staff": false,
  "is_active": true
}:
Accept: application/json
Content-Length: 0
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.13 (Java/17.0.5)
Accept-Encoding: br,deflate,gzip,x-gzip

